import type { IngredientModel } from "@/hooks/queries/recipeQueries"

/**
 * Given a direction string,
 * and a list of ingredients,
 * returns the ingredients that are likely being referred to in the direction.
 *
 * This file was in large part generated by VSCode Copilot, GPT-5.4 mini.
 */

const IGNORED_INGREDIENT_TOKENS = new Set([
  "all",
  "purpose",
  "fresh",
  "chopped",
  "sliced",
  "diced",
  "minced",
  "ground",
  "grated",
  "shredded",
  "crushed",
  "peeled",
  "seeded",
  "softened",
  "melted",
  "warm",
  "cold",
  "room",
  "temperature",
  "packed",
  "optional",
  "boneless",
  "skinless",
])

export const formatIngredientAmount = (amount: number): string =>
  new Intl.NumberFormat("en-US", {
    maximumFractionDigits: 2,
    minimumFractionDigits: 0,
    useGrouping: false,
  }).format(amount)

const normalizeText = (value: string): string =>
  value
    .toLowerCase()
    .replace(/[`']/g, "")
    .replace(/[^a-z0-9]+/g, " ")
    .replace(/\s+/g, " ")
    .trim()

const singularizeToken = (token: string): string => {
  if (token.length > 4 && token.endsWith("ies")) {
    return `${token.slice(0, -3)}y`
  }

  if (token.length > 3 && token.endsWith("es")) {
    return token.slice(0, -2)
  }

  if (token.length > 3 && token.endsWith("s")) {
    return token.slice(0, -1)
  }

  return token
}

const tokenize = (value: string): string[] =>
  normalizeText(value).split(" ").filter(Boolean).map(singularizeToken)

const getIngredientTokens = (ingredientName: string): string[] => {
  const uniqueTokens = new Set(
    tokenize(ingredientName).filter(
      (token) => !IGNORED_INGREDIENT_TOKENS.has(token)
    )
  )

  return Array.from(uniqueTokens)
}

const scoreIngredientMatch = (
  directionTokens: Set<string>,
  normalizedDirection: string,
  ingredientName: string
) => {
  const tokens = getIngredientTokens(ingredientName)

  if (tokens.length === 0) {
    return null
  }

  const headToken = tokens[tokens.length - 1]
  const modifierTokens = tokens.slice(0, -1)
  const phrase = tokens.join(" ")
  const paddedDirection = ` ${normalizedDirection} `
  const phraseMatch =
    phrase.length > 0 && paddedDirection.includes(` ${phrase} `)

  const matchedTokens = tokens.filter((token) => directionTokens.has(token))
  const tokenCoverage = matchedTokens.length / tokens.length
  const headMatch = directionTokens.has(headToken)
  const modifierHits = modifierTokens.filter((token) =>
    directionTokens.has(token)
  ).length

  if (!headMatch && !phraseMatch) {
    return null
  }

  let score = 0

  if (phraseMatch) {
    score += 3
  }

  if (tokenCoverage === 1) {
    score += 2
  } else if (headMatch) {
    score += 1
  }

  score += modifierHits * 0.5

  return {
    ingredientName,
    tokens,
    headToken,
    modifierCount: modifierTokens.length,
    score,
    strongMatch: phraseMatch || tokenCoverage === 1,
  }
}

export const getIngredientsForStep = (
  directionText: string,
  ingredients: IngredientModel[]
): IngredientModel[] => {
  const normalizedDirection = normalizeText(directionText)
  const directionTokens = new Set(tokenize(directionText))

  const scoredIngredients = ingredients
    .map((ingredient, index) => ({
      ingredient,
      index,
      match: scoreIngredientMatch(
        directionTokens,
        normalizedDirection,
        ingredient.name
      ),
    }))
    .filter(
      (
        entry
      ): entry is {
        ingredient: IngredientModel
        index: number
        match: NonNullable<ReturnType<typeof scoreIngredientMatch>>
      } => entry.match !== null
    )

  const groupedByHeadToken = new Map<string, typeof scoredIngredients>()

  for (const entry of scoredIngredients) {
    const matchesForHead = groupedByHeadToken.get(entry.match.headToken) ?? []
    matchesForHead.push(entry)
    groupedByHeadToken.set(entry.match.headToken, matchesForHead)
  }

  const selectedIngredients: IngredientModel[] = []

  for (const matchesForHead of groupedByHeadToken.values()) {
    const strongMatches = matchesForHead.filter(
      (entry) => entry.match.strongMatch
    )

    const candidates =
      strongMatches.length > 0 ? strongMatches : matchesForHead.slice()

    candidates.sort((left, right) => {
      if (right.match.score !== left.match.score) {
        return right.match.score - left.match.score
      }

      if (left.match.modifierCount !== right.match.modifierCount) {
        return left.match.modifierCount - right.match.modifierCount
      }

      return left.index - right.index
    })

    if (strongMatches.length > 0) {
      selectedIngredients.push(...candidates.map((entry) => entry.ingredient))
      continue
    }

    selectedIngredients.push(candidates[0].ingredient)
  }

  return selectedIngredients
}
